# Site settings
title: medhistree.com
email: medhistree@sheprograms.com
description: > # this means to ignore newlines until "baseurl:"
  Your medical history doesn't just belong to you - it belongs to your entire
  family.  Share your medical stories with those you care about, and
  collaborate with your family to create a more complete picture of your
  health.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://medhistree.com" # the base hostname & protocol for your site
twitter_username: medhistree

# Build settings
markdown: kramdown
